import { FAQItem } from '@/components/ui/faq-accordion';

export interface CardItem { title: string; description: string; }
export interface QuickRow { label: string; formula: string; notes: string; }
export interface LinkItem { label: string; url: string; }

export interface VariantConfig {
  title: string;
  subtitle: string;
  cta: string;
  reviewName: string;
  focus: string;
  concept: string;
  stepTips: string[];
  dashboardTips: string[];
  features: string[];
  quickRows: QuickRow[];
  references: LinkItem[];
  whyUse: CardItem[];
  understanding: CardItem[];
  faqs: FAQItem[];
}

const faq = (question: string, answer: string, category: string): FAQItem => ({ question, answer, category });
const row = (label: string, formula: string, notes: string): QuickRow => ({ label, formula, notes });
const card = (title: string, description: string): CardItem => ({ title, description });

export const REF = {
  quadratics: { label: 'OpenStax: Quadratic Equations', url: 'https://openstax.org/books/algebra-and-trigonometry-2e/pages/2-5-quadratic-equations' },
  systems: { label: 'OpenStax: Systems of Linear Equations', url: 'https://openstax.org/books/college-algebra-corequisite-support-2e/pages/7-1-systems-of-linear-equations-two-variables' },
  polynomials: { label: 'OpenStax: Graphs of Polynomial Functions', url: 'https://openstax.org/books/algebra-and-trigonometry/pages/5-3-graphs-of-polynomial-functions' },
  logs: { label: 'OpenStax: Logarithmic Functions', url: 'https://openstax.org/books/college-algebra-2e/pages/6-3-logarithmic-functions' },
  radicals: { label: 'OpenStax: Radicals and Rational Exponents', url: 'https://openstax.org/books/algebra-and-trigonometry-2e/pages/1-3-radicals-and-rational-exponents' },
  slope: { label: 'Khan Academy: Slope Formula', url: 'https://www.khanacademy.org/math/pre-algebra/xb4832e56%3Atwo-variable-equations/xb4832e56%3Aslope/a/slope-formula' },
  distance: { label: 'Khan Academy: Distance Formula', url: 'https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry/hs-geo-distance-and-midpoints/a/distance-formula' },
  analytic: { label: 'Khan Academy: Analytic Geometry', url: 'https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry' },
  notation: { label: 'Khan Academy: Roots, Exponents, and Scientific Notation', url: 'https://www.khanacademy.org/math/pre-algebra/exponents-radicals' },
  absolute: { label: 'OpenStax: Absolute Value Functions', url: 'https://openstax.org/books/college-algebra-corequisite-support/pages/3-6-absolute-value-functions' },
};

export type AlgebraVariant =
  | 'quadratic-formula' | 'slope' | 'distance-formula' | 'midpoint' | 'linear-equation'
  | 'system-of-equations' | 'polynomial' | 'factoring' | 'exponent' | 'logarithm'
  | 'scientific-notation' | 'square-root' | 'cube-root' | 'nth-root' | 'absolute-value';

export const DEFAULT_INPUTS = {
  a: '1', b: '-3', c: '-4', d: '8',
  x1: '2', y1: '3', x2: '8', y2: '15',
  a1: '2', b1: '3', c1: '13', a2: '1', b2: '-1', c2: '1',
  base: '2', exponent: '5', logValue: '64',
  radicand: '72', index: '4', absoluteInput: '-12',
  polynomialCoefficients: '1, -3, -4', xValue: '2',
  decimalInput: '0.000345', mantissa: '3.45', sciExponent: '-4',
  notationMode: 'decimal-to-scientific' as const,
};

const baseWhyUse = [
  card('Exact + decimal framing', 'Keep symbolic structure and practical estimates together.'),
  card('Context beyond one answer', 'Classification and supporting values stay attached to the result.'),
  card('Popup-only results', 'The result flow matches the approved advanced calculator pattern.'),
  card('Better checking discipline', 'Warnings reduce hidden mistakes and bad assumptions.'),
];

const cfg = (
  title: string, subtitle: string, cta: string, reviewName: string, focus: string, concept: string,
  stepTips: string[], dashboardTips: string[], features: string[], quickRows: QuickRow[],
  references: LinkItem[], understanding: CardItem[], faqs: FAQItem[]
): VariantConfig => ({ title, subtitle, cta, reviewName, focus, concept, stepTips, dashboardTips, features, quickRows, references, whyUse: baseWhyUse, understanding, faqs });

export const ALGEBRA_CONFIG: Record<AlgebraVariant, VariantConfig> = {
  'quadratic-formula': cfg('Quadratic Formula Calculator', 'Solve quadratics with exact roots, decimal roots, and discriminant context', 'Solve Quadratic Equation', 'Quadratic Formula Calculator', 'quadratic-equation solving', 'quadratic equations', ['Enter a, b, and c from ax^2 + bx + c = 0.', 'Check the discriminant first because it classifies the roots.', 'Read exact form before decimals when checking algebra.', 'Use axis and vertex values to connect solving with graph behavior.'], ['Exact and decimal roots', 'Discriminant and root type', 'Axis of symmetry', 'Vertex coordinates'], ['Exact radical form', 'Decimal root pair', 'Discriminant classification', 'Axis and vertex context', 'Repeated-root handling', 'Complex-root warning'], [row('Quadratic formula', 'x = (-b +/- sqrt(b^2 - 4ac)) / 2a', 'Core solving formula.'), row('Discriminant', 'D = b^2 - 4ac', 'Classifies root type.'), row('Axis', 'x = -b / 2a', 'Passes through the vertex.'), row('Root types', 'D > 0, D = 0, D < 0', 'Real pair, repeated root, or complex pair.')], [REF.quadratics, REF.polynomials], [card('Discriminant', 'The discriminant explains root behavior before solving finishes.'), card('Exact form', 'Radical form preserves more algebra than a rounded decimal.'), card('Vertex link', 'Quadratic solving and parabola analysis are closely related.')], [faq('Why does the calculator show the discriminant?', 'Because the discriminant is the fastest way to understand what kind of roots the quadratic has.', 'Method'), faq('Why are exact and decimal answers both shown?', 'Exact answers preserve the algebra while decimals help with estimation and graphing.', 'Results')]),
  slope: cfg('Slope Calculator', 'Find slope from two points and connect it to line equations and direction', 'Calculate Slope', 'Slope Calculator', 'line analysis from two coordinates', 'slope and line equations', ['Enter two coordinates.', 'Compare rise and run before reading the slope.', 'Use the line-equation output to make the answer actionable.', 'Check the warning if the line is vertical or the two points match.'], ['Slope fraction and decimal', 'Rise and run', 'Line equation', 'Direction angle'], ['Simplified fraction output', 'Vertical-line handling', 'Horizontal-line recognition', 'Line-equation context', 'Angle estimate', 'Duplicate-point warning'], [row('Slope', 'm = (y2 - y1) / (x2 - x1)', 'Undefined when the run is zero.'), row('Point-slope form', 'y - y1 = m(x - x1)', 'Useful once the slope is known.'), row('Slope-intercept form', 'y = mx + b', 'Works for nonvertical lines.'), row('Horizontal line', 'm = 0', 'No vertical change.')], [REF.slope, REF.analytic], [card('Rise over run', 'Slope compares vertical change with horizontal change.'), card('Undefined slope', 'A vertical line still has a valid equation even though the slope is undefined.'), card('Equation context', 'Slope becomes much more useful once it is attached to a line equation.')], [faq('Why can slope be undefined?', 'Because a vertical line has zero horizontal change, so the slope ratio would divide by zero.', 'Basics'), faq('Why show the line equation too?', 'Because the slope is usually more useful once it is attached to an actual line.', 'Results')]),
  'distance-formula': cfg('Distance Formula Calculator', 'Measure exact and decimal distance between two points on the coordinate plane', 'Calculate Distance', 'Distance Formula Calculator', 'coordinate-plane distance measurement', 'distance between two points', ['Enter both endpoints.', 'Use the horizontal and vertical changes as the triangle legs.', 'Read exact radical form before the decimal when checking algebra.', 'Keep squared distance in view if you want a faster arithmetic check.'], ['Exact distance', 'Decimal distance', 'Horizontal change', 'Squared distance'], ['Exact radical simplification', 'Decimal estimate', 'Delta x and delta y context', 'Squared-distance checkpoint', 'Useful for analytic geometry', 'Matches the approved advanced results flow'], [row('Distance', 'd = sqrt((x2 - x1)^2 + (y2 - y1)^2)', 'Built from the Pythagorean theorem.'), row('Horizontal change', 'delta x = x2 - x1', 'One leg of the right triangle.'), row('Vertical change', 'delta y = y2 - y1', 'The other leg of the triangle.'), row('Squared distance', 'd^2 = (delta x)^2 + (delta y)^2', 'Helpful before taking the root.')], [REF.distance, REF.radicals], [card('Pythagorean link', 'Distance on the coordinate plane comes from a right triangle model.'), card('Exact radicals', 'Exact form is often stronger than a rounded decimal for algebra.'), card('Squared-distance check', 'Seeing the radicand helps you catch arithmetic mistakes early.')], [faq('Why are exact and decimal answers both useful?', 'Exact radicals are better for algebra, while decimals are easier for estimation and graphing.', 'Results'), faq('Can distance ever be negative?', 'No. Distance measures length, so it is always zero or positive.', 'Basics')]),
  midpoint: cfg('Midpoint Calculator', 'Find the point halfway between two coordinates and keep segment context visible', 'Find Midpoint', 'Midpoint Calculator', 'segment-center analysis', 'midpoints and coordinate averages', ['Enter both endpoints.', 'Average x-values and y-values separately.', 'Use slope and distance context to sanity-check the segment.', 'Carry the midpoint directly into your next geometry or algebra step.'], ['Midpoint coordinates', 'Segment length', 'Slope context', 'Coordinate averages'], ['Midpoint coordinates', 'Distance context', 'Slope support', 'Center-point verification', 'Useful for bisectors and symmetry', 'Same advanced layout as the reference tools'], [row('Midpoint', '((x1 + x2)/2, (y1 + y2)/2)', 'Average x and y separately.'), row('Distance check', 'Use the distance formula', 'The midpoint should split the segment equally.'), row('Slope context', 'm = delta y / delta x', 'Useful for segment interpretation.'), row('Identical endpoints', 'Midpoint = endpoint', 'If both points are the same, the midpoint is that same point.')], [REF.analytic, REF.distance], [card('Averages', 'Midpoint is an average problem in coordinate form.'), card('Segment checks', 'Distance and slope help confirm the segment geometry.'), card('Why midpoint appears often', 'It is central to symmetry, bisectors, and coordinate proofs.')], [faq('Why does midpoint use averages?', 'Because the center point must be equally far from both endpoints in the x- and y-directions.', 'Method'), faq('Does midpoint depend on slope?', 'No. Slope describes direction, while midpoint describes the center.', 'Basics')]),
  'linear-equation': cfg('Linear Equation Calculator', 'Solve one-variable linear equations and classify unique, infinite, or no-solution cases', 'Solve Linear Equation', 'Linear Equation Calculator', 'one-variable linear equation solving', 'linear equations', ['Enter coefficients for ax + b = cx + d.', 'Reduce the problem to one x-term and one constant term.', 'Read the classification before the answer value.', 'Use exact fractions when the division does not come out cleanly.'], ['Exact solution', 'Decimal solution', 'Reduced equation', 'Special-case classification'], ['Handles x on both sides', 'Exact fraction output', 'No-solution recognition', 'Infinite-solution recognition', 'Reduced-form context', 'Consistent advanced tool structure'], [row('General form', 'ax + b = cx + d', 'This is the equation format used here.'), row('Reduced form', '(a - c)x = d - b', 'Bring variable terms together.'), row('Unique solution', 'a - c != 0', 'A nonzero coefficient on x gives one solution.'), row('Special case', 'a - c = 0', 'Then the constants decide whether the equation is always true or false.')], [REF.systems, REF.absolute], [card('Cancellation', 'When x terms cancel, the problem changes type entirely.'), card('Fractions', 'Exact fractions often preserve the true solution more cleanly than decimals.'), card('Classification first', 'Unique, infinite, and no-solution cases are different algebra stories.')], [faq('Why can a linear equation have no solution?', 'Because the variable terms can cancel while the constants still disagree.', 'Special Cases'), faq('Why can it have infinitely many solutions?', 'Because both sides can reduce to the same statement.', 'Special Cases')]),
  'system-of-equations': cfg('System of Equations Calculator', 'Solve 2x2 systems with determinant checks and exact-fraction support', 'Solve System', 'System of Equations Calculator', 'two-variable system solving', 'systems of linear equations', ['Enter both equations in coefficient form.', 'Check the determinant first because it signals whether the solution is unique.', 'Use exact fractions when checking schoolwork or symbolic steps.', 'Read the classification if the determinant is zero because the system may be parallel or dependent.'], ['Solution pair', 'Determinant', 'Exact fractions', 'Unique/no/infinite classification'], ['2x2 coefficient input', 'Determinant-based classification', 'Exact x and y output', 'Decimal pair for graphing', 'Parallel/dependent warnings', 'Advanced educational content pattern'], [row('System form', 'a1x + b1y = c1 and a2x + b2y = c2', 'Enter coefficients directly.'), row('Determinant', 'a1b2 - a2b1', 'Signals whether the coefficient matrix is invertible.'), row('Unique x', 'x = (c1b2 - c2b1)/det', 'Works when the determinant is nonzero.'), row('Unique y', 'y = (a1c2 - a2c1)/det', 'Works when the determinant is nonzero.')], [REF.systems, REF.slope], [card('Determinant', 'A nonzero determinant usually means one unique intersection.'), card('Parallel systems', 'Parallel lines never meet, so the system has no solution.'), card('Dependent systems', 'The same line repeated creates infinitely many solutions.')], [faq('Why does the calculator show the determinant?', 'Because it is a fast signal for whether a unique 2x2 solution exists.', 'Method'), faq('Why can a system have infinitely many solutions?', 'Because both equations can describe the same line.', 'Special Cases')]),
  polynomial: cfg('Polynomial Calculator', 'Evaluate a polynomial, inspect its degree, and keep derivative context visible', 'Analyze Polynomial', 'Polynomial Calculator', 'polynomial evaluation and structure', 'polynomials', ['Enter coefficients from highest degree to constant term.', 'Enter the x-value where you want to evaluate the polynomial.', 'Use the derivative output if you want local rate-of-change context.', 'Treat possible integer roots as screening hints, not guaranteed roots.'], ['P(x) value', 'Polynomial expression', 'Derivative expression', 'Possible integer roots'], ['Comma-based coefficients', 'Automatic expression rendering', 'Derivative support', 'Degree context', 'Possible integer-root hints', 'Useful bridge between algebra and graphing'], [row('Coefficient order', 'highest degree to constant', 'Descending order matters.'), row('Polynomial value', 'P(x)', 'The main evaluation target.'), row('Derivative', "P'(x)", 'Adds slope context at the chosen x-value.'), row('Degree', 'highest nonzero exponent', 'Helps frame the polynomial structure.')], [REF.polynomials, REF.quadratics], [card('Coefficients', 'The coefficients shape the expression before you ever graph it.'), card('Derivative use', 'Derivative values give local behavior, not just a static point value.'), card('Root candidates', 'Candidate roots still need testing in the polynomial.')], [faq('Why use coefficients instead of typing a full expression?', 'Coefficient entry is easier to validate consistently and makes the degree explicit immediately.', 'Inputs'), faq('Why show the derivative?', 'Because it adds rate-of-change context that basic evaluators skip.', 'Results')]),
  factoring: cfg('Factoring Calculator', 'Factor quadratic expressions and connect the result directly to root behavior', 'Factor Expression', 'Factoring Calculator', 'quadratic factoring and root interpretation', 'factoring', ['Enter the quadratic coefficients a, b, and c.', 'Use the discriminant to understand whether a clean factorization is likely.', 'Read the factorization and root pair together.', 'Treat "not factorable cleanly" as a real result, not a calculator failure.'], ['Factored form', 'Root pair', 'Discriminant', 'Factorability note'], ['Quadratic factoring focus', 'Root-aware output', 'Integer-versus-rational distinction', 'Discriminant context', 'Irreducible-case warning', 'Advanced layout consistency'], [row('Quadratic form', 'ax^2 + bx + c', 'This calculator factors quadratics from coefficients.'), row('Root link', '(x - r1)(x - r2)', 'Roots and factors are connected.'), row('Repeated root', 'D = 0', 'Often means a squared linear factor.'), row('Prime over integers', 'no clean integer factor pair', 'Some quadratics do not factor nicely over the integers.')], [REF.quadratics, REF.polynomials], [card('Factors and roots', 'Factoring rewrites the expression in a way that exposes the roots.'), card('When factoring is hard', 'Irrational or complex roots can block a neat integer factor pair.'), card('Discriminant again', 'Even on a factoring page, the discriminant is a fast structural signal.')], [faq('Why does the calculator sometimes say the expression does not factor cleanly?', 'Because not every quadratic has an integer-friendly factor pair, even when real roots exist.', 'Results'), faq('Why show roots on a factoring page?', 'Because factors and roots are two views of the same quadratic.', 'Method')]),
  exponent: cfg('Exponent Calculator', 'Evaluate powers and explain negative exponents, fractional exponents, and scale', 'Calculate Exponent', 'Exponent Calculator', 'power evaluation and exponent meaning', 'exponents', ['Enter the base and exponent.', 'Use the reciprocal note when the exponent is negative.', 'Check the warning if the base is negative and the exponent is not an integer.', 'Use scientific notation when the result becomes very large or very small.'], ['Power result', 'Reciprocal lens', 'Scientific notation', 'Result type'], ['Positive and negative exponent support', 'Fractional exponent handling', 'Scientific-notation output', 'Real-number domain checks', 'Reciprocal interpretation', 'Useful bridge to roots and logs'], [row('Power', 'a^n', 'Exponent tells how the base is used multiplicatively.'), row('Negative exponent', 'a^-n = 1 / a^n', 'Creates a reciprocal.'), row('Zero exponent', 'a^0 = 1', 'For nonzero a.'), row('Rational exponent', 'a^(m/n)', 'Connects powers to roots.')], [REF.radicals, REF.notation], [card('Negative exponents', 'They change where the power lives rather than automatically changing the sign.'), card('Fractional exponents', 'They connect directly to radicals.'), card('Domain checks', 'Some base/exponent pairs do not stay inside the real numbers.')], [faq('Why is a negative exponent not the same as a negative answer?', 'Because a negative exponent creates a reciprocal, not a negative sign by itself.', 'Basics'), faq('Why are some fractional exponents invalid for negative bases?', 'Because the corresponding root may not be real.', 'Domain')]),
  logarithm: cfg('Logarithm Calculator', 'Evaluate logs with arbitrary bases and connect them back to exponent form', 'Calculate Logarithm', 'Logarithm Calculator', 'logarithmic evaluation and interpretation', 'logarithms', ['Enter the base and the argument value.', 'Check that the base is positive and not equal to 1.', 'Check that the argument is positive.', 'Read the exponential-form check after the decimal answer.'], ['Main log value', 'Exponential-form check', 'Change-of-base context', 'ln and log10 comparison'], ['Arbitrary-base support', 'Exponential-form translation', 'Change-of-base explanation', 'Domain checks', 'Natural/common-log context', 'Advanced educational copy'], [row('Definition', 'y = log_b(x) means b^y = x', 'Logs are exponents in disguise.'), row('Base rule', 'b > 0 and b != 1', 'A valid real base must follow these rules.'), row('Argument rule', 'x > 0', 'The real logarithm needs a positive argument.'), row('Change of base', 'log_b(x) = ln(x) / ln(b)', 'Useful for arbitrary-base evaluation.')], [REF.logs, REF.radicals], [card('Logs as exponents', 'A logarithm tells you which exponent creates the argument from the base.'), card('Base and argument rules', 'The domain rules are part of the problem, not extra trivia.'), card('Change of base', 'This is the bridge from arbitrary bases to familiar logs.')], [faq("Why can't the logarithm of a negative number be shown here?", 'Because real-number logarithms require a positive argument.', 'Domain'), faq('Why does the page show exponential form too?', 'Because it is the clearest way to interpret the logarithm result.', 'Method')]),
  'scientific-notation': cfg('Scientific Notation Calculator', 'Convert between decimal and scientific notation with normalized mantissa checks', 'Convert Notation', 'Scientific Notation Calculator', 'scientific-notation conversion', 'scientific notation', ['Choose the conversion mode first.', 'Enter either the decimal number or the mantissa/exponent pair.', 'Check that the mantissa is normalized when appropriate.', 'Use the exponent shift to verify the decimal movement.'], ['Converted value', 'Mantissa', 'Exponent', 'Normalization context'], ['Two conversion modes', 'Normalized-form checks', 'Power-of-ten framing', 'Large/small number readability', 'Zero handling', 'Same advanced layout standard as other new tools'], [row('Scientific form', 'a x 10^n', 'Use a normalized mantissa for standard notation.'), row('Large number', 'positive exponent', 'Decimal moves left.'), row('Small number', 'negative exponent', 'Decimal moves right.'), row('Zero', '0 x 10^0', 'Zero is a special case.')], [REF.notation, REF.radicals], [card('Why notation exists', 'Scientific notation separates scale from mantissa so magnitude is easier to read.'), card('Normalization', 'Standard form keeps the mantissa between 1 and 10 in absolute value.'), card('Exponent shift', 'The exponent records how far the decimal had to move.')], [faq('Why does the mantissa have to be between 1 and 10?', 'That normalization rule keeps scientific notation consistent and readable.', 'Basics'), faq('Why does a tiny decimal produce a negative exponent?', 'Because the decimal has to move right to normalize, which corresponds to a negative power of ten.', 'Method')]),
  'square-root': cfg('Square Root Calculator', 'Show exact radical simplification and decimal square-root values side by side', 'Calculate Square Root', 'Square Root Calculator', 'square-root simplification and estimation', 'square roots', ['Enter the radicand.', 'Check whether the number is a perfect square.', 'Read the exact radical form before the decimal for algebra work.', 'Use the nearest perfect squares if you want a fast estimate check.'], ['Exact radical', 'Decimal root', 'Nearest perfect squares', 'Radicand context'], ['Exact radical simplification', 'Decimal approximation', 'Perfect-square detection', 'Irrational-root framing', 'Real-number domain warning', 'Advanced content depth instead of a thin widget'], [row('Square root', 'sqrt(x)', 'Asks which number squared gives x.'), row('Perfect square', 'x = n^2', 'Then sqrt(x) = n exactly.'), row('Simplification', 'sqrt(ab) = sqrt(a) x sqrt(b)', 'Useful when a contains a perfect-square factor.'), row('Real-number rule', 'x >= 0', 'Negative radicands are not real square roots.')], [REF.radicals, REF.distance], [card('Simplification', 'Pulling out perfect-square factors keeps the radical cleaner.'), card('Irrational answers', 'Many square roots are supposed to stay radical.'), card('Domain rule', 'Real square roots require nonnegative radicands.')], [faq('Why show exact and decimal answers together?', 'Because exact radicals are better for algebra while decimals are better for estimation.', 'Results'), faq("Why can't a negative number have a real square root here?", 'Because no real number squared becomes negative.', 'Domain')]),
  'cube-root': cfg('Cube Root Calculator', 'Evaluate cube roots with exact simplification and decimal output, including negatives', 'Calculate Cube Root', 'Cube Root Calculator', 'cube-root evaluation and simplification', 'cube roots', ['Enter the radicand.', 'Check whether the input is a perfect cube.', 'Read the exact radical if you are simplifying algebraically.', 'Use the decimal if you just need a size estimate.'], ['Exact cube-root form', 'Decimal cube root', 'Perfect-cube check', 'Negative-input handling'], ['Negative radicand support', 'Perfect-cube extraction', 'Decimal estimate', 'Useful for volume and scaling', 'Odd-root sign behavior', 'Long-form advanced content treatment'], [row('Cube root', 'cbrt(x)', 'Asks which number cubed gives x.'), row('Perfect cube', 'x = n^3', 'Then cbrt(x) = n exactly.'), row('Odd-root sign rule', 'cbrt(-x) = -cbrt(x)', 'Negative radicands stay real.'), row('Simplification', 'cbrt(ab) = cbrt(a) x cbrt(b)', 'Useful when a contains a perfect-cube factor.')], [REF.radicals, REF.notation], [card('Odd roots', 'Odd roots preserve sign inside the real numbers.'), card('Perfect cubes', 'Cube factors simplify the exact radical form.'), card('Beyond drills', 'Cube roots show up in volume and scaling contexts often.')], [faq('Why can the cube root of a negative number be real?', 'Because a negative number cubed stays negative, so the inverse operation stays real.', 'Basics'), faq('Why does the answer sometimes remain in radical form?', 'Because not every radicand contains a perfect-cube factor.', 'Results')]),
  'nth-root': cfg('Nth Root Calculator', 'Evaluate higher-order roots with index-aware simplification and domain checks', 'Calculate Nth Root', 'Nth Root Calculator', 'higher-order root evaluation', 'nth roots', ['Enter the root index and radicand.', 'Check the index before interpreting the sign rules.', 'Read the exact radical form when symbolic structure matters.', 'Use the domain warning for even roots of negative values.'], ['Exact nth-root form', 'Decimal approximation', 'Index context', 'Odd/even rule'], ['Higher-order root support', 'Odd/even index checks', 'Exact simplification when possible', 'Bridge to rational exponents', 'Domain warnings', 'Same approved advanced page structure'], [row('Nth root', 'nthRoot(x, n)', 'Asks which number raised to n gives x.'), row('Even index', 'negative radicand invalid in reals', 'Even roots of negatives are not real.'), row('Odd index', 'negative radicand allowed', 'Odd roots can stay real.'), row('Exponent link', 'x^(1/n)', 'Nth roots and rational exponents match conceptually.')], [REF.radicals, REF.logs], [card('Why index matters', 'The index determines which power is being reversed.'), card('Odd/even behavior', 'Even and odd roots follow different sign rules.'), card('Exponent link', 'Nth roots are another way to read x^(1/n).')], [faq('Why does the same negative radicand sometimes work and sometimes fail?', 'Because odd roots can stay real while even roots cannot.', 'Domain'), faq('Why does the index get so much attention?', 'Because it controls both the value and the domain rules.', 'Method')]),
  'absolute-value': cfg('Absolute Value Calculator', 'Measure magnitude as distance from zero and keep sign context visible', 'Calculate Absolute Value', 'Absolute Value Calculator', 'absolute-value magnitude', 'absolute value', ['Enter the number you want to measure.', 'Read the answer as distance from zero, not just "remove the sign".', 'Use the sign note to connect the answer back to the original input.', 'Keep the piecewise lens in mind if you are moving into equations or graphs next.'], ['Absolute value', 'Distance from zero', 'Original sign', 'Piecewise lens'], ['Distance-based interpretation', 'Sign-aware notes', 'Piecewise-function context', 'Opposite-value support', 'Simple input with stronger explanation', 'Advanced content length instead of a thin answer box'], [row('Absolute value', '|x|', 'Measures distance from zero.'), row('Positive input', '|x| = x', 'If x is nonnegative, it stays the same.'), row('Negative input', '|x| = -x', 'A negative input flips to its positive magnitude.'), row('Distance rule', '|x| >= 0', 'Absolute value cannot be negative.')], [REF.absolute, REF.absolute], [card('Distance', 'Absolute value is distance from zero, not just sign removal.'), card('Sign versus magnitude', 'Two numbers can point in opposite directions but share the same magnitude.'), card('Piecewise idea', 'Absolute value later becomes piecewise because the rule depends on sign.')], [faq('Why is absolute value never negative?', 'Because distance cannot be negative.', 'Basics'), faq('Why do 5 and -5 have the same absolute value?', 'Because they are the same distance from zero on opposite sides of the number line.', 'Meaning')]),
};
